# Setup
title:        SEWUNet
tagline:      Monaural Speech Enhancement through Deep Wave-U-Net
baseurl:      "http://hguimaraes.me/SEWUNet"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Heitor Guimarães
  url:        http://hguimaraes.me 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown